//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.smartid {

public class ImageField : global::System.IDisposable {
  private global::System.Runtime.InteropServices.SafeHandle swigCPtr;
  protected bool swigCMemOwn;

  internal ImageField(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(cPtr, false);
  }

  internal static global::System.Runtime.InteropServices.SafeHandle getCPtr(ImageField obj) {
    return (obj == null) ? new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(global::System.IntPtr.Zero, false) : obj.swigCPtr;
  }

  ~ImageField() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr != null && swigCPtr.DangerousGetHandle() != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csSmartIdEnginePINVOKE.delete_ImageField(swigCPtr.DangerousGetHandle());
        }
        swigCPtr = new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(global::System.IntPtr.Zero, false);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public ImageField() : this(csSmartIdEnginePINVOKE.new_ImageField__SWIG_0(), true) {
  }

  public ImageField(string name, Image value, bool is_accepted, double confidence, StringCollection attributes) : this(csSmartIdEnginePINVOKE.new_ImageField__SWIG_1(name, Image.getCPtr(value).DangerousGetHandle(), is_accepted, confidence, StringCollection.getCPtr(attributes).DangerousGetHandle()), true) {
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public ImageField(string name, Image value, bool is_accepted, double confidence) : this(csSmartIdEnginePINVOKE.new_ImageField__SWIG_2(name, Image.getCPtr(value).DangerousGetHandle(), is_accepted, confidence), true) {
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetName() {
    string ret = csSmartIdEnginePINVOKE.ImageField_GetName(swigCPtr.DangerousGetHandle());
    return ret;
  }

  public Image GetValue() {
    Image ret = new Image(csSmartIdEnginePINVOKE.ImageField_GetValue(swigCPtr.DangerousGetHandle()), false);
    return ret;
  }

  public bool IsAccepted() {
    bool ret = csSmartIdEnginePINVOKE.ImageField_IsAccepted(swigCPtr.DangerousGetHandle());
    return ret;
  }

  public double GetConfidence() {
    double ret = csSmartIdEnginePINVOKE.ImageField_GetConfidence(swigCPtr.DangerousGetHandle());
    return ret;
  }

  public StringVector GetAttributeNames() {
    StringVector ret = new StringVector(csSmartIdEnginePINVOKE.ImageField_GetAttributeNames(swigCPtr.DangerousGetHandle()), true);
    return ret;
  }

  public StringCollection GetAttributes() {
    StringCollection ret = new StringCollection(csSmartIdEnginePINVOKE.ImageField_GetAttributes(swigCPtr.DangerousGetHandle()), false);
    return ret;
  }

  public bool HasAttribute(string attribute_name) {
    bool ret = csSmartIdEnginePINVOKE.ImageField_HasAttribute(swigCPtr.DangerousGetHandle(), attribute_name);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string GetAttribute(string attribute_name) {
    string ret = csSmartIdEnginePINVOKE.ImageField_GetAttribute(swigCPtr.DangerousGetHandle(), attribute_name);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

}

}
