//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.smartid {

public class MatchResult : global::System.IDisposable {
  private global::System.Runtime.InteropServices.SafeHandle swigCPtr;
  protected bool swigCMemOwn;

  internal MatchResult(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(cPtr, false);
  }

  internal static global::System.Runtime.InteropServices.SafeHandle getCPtr(MatchResult obj) {
    return (obj == null) ? new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(global::System.IntPtr.Zero, false) : obj.swigCPtr;
  }

  ~MatchResult() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr != null && swigCPtr.DangerousGetHandle() != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csSmartIdEnginePINVOKE.delete_MatchResult(swigCPtr.DangerousGetHandle());
        }
        swigCPtr = new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(global::System.IntPtr.Zero, false);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public MatchResult() : this(csSmartIdEnginePINVOKE.new_MatchResult__SWIG_0(), true) {
  }

  public MatchResult(string tpl_type, Quadrangle quadrangle, bool accepted, double confidence, int standard_width, int standard_height) : this(csSmartIdEnginePINVOKE.new_MatchResult__SWIG_1(tpl_type, Quadrangle.getCPtr(quadrangle).DangerousGetHandle(), accepted, confidence, standard_width, standard_height), true) {
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public MatchResult(string tpl_type, Quadrangle quadrangle, bool accepted, double confidence, int standard_width) : this(csSmartIdEnginePINVOKE.new_MatchResult__SWIG_2(tpl_type, Quadrangle.getCPtr(quadrangle).DangerousGetHandle(), accepted, confidence, standard_width), true) {
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public MatchResult(string tpl_type, Quadrangle quadrangle, bool accepted, double confidence) : this(csSmartIdEnginePINVOKE.new_MatchResult__SWIG_3(tpl_type, Quadrangle.getCPtr(quadrangle).DangerousGetHandle(), accepted, confidence), true) {
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public MatchResult(string tpl_type, Quadrangle quadrangle, bool accepted) : this(csSmartIdEnginePINVOKE.new_MatchResult__SWIG_4(tpl_type, Quadrangle.getCPtr(quadrangle).DangerousGetHandle(), accepted), true) {
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public MatchResult(string tpl_type, Quadrangle quadrangle) : this(csSmartIdEnginePINVOKE.new_MatchResult__SWIG_5(tpl_type, Quadrangle.getCPtr(quadrangle).DangerousGetHandle()), true) {
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public string GetTemplateType() {
    string ret = csSmartIdEnginePINVOKE.MatchResult_GetTemplateType(swigCPtr.DangerousGetHandle());
    return ret;
  }

  public Quadrangle GetQuadrangle() {
    Quadrangle ret = new Quadrangle(csSmartIdEnginePINVOKE.MatchResult_GetQuadrangle(swigCPtr.DangerousGetHandle()), false);
    return ret;
  }

  public int GetStandardWidth() {
    int ret = csSmartIdEnginePINVOKE.MatchResult_GetStandardWidth(swigCPtr.DangerousGetHandle());
    return ret;
  }

  public int GetStandardHeight() {
    int ret = csSmartIdEnginePINVOKE.MatchResult_GetStandardHeight(swigCPtr.DangerousGetHandle());
    return ret;
  }

  public bool GetAccepted() {
    bool ret = csSmartIdEnginePINVOKE.MatchResult_GetAccepted(swigCPtr.DangerousGetHandle());
    return ret;
  }

  public double GetConfidence() {
    double ret = csSmartIdEnginePINVOKE.MatchResult_GetConfidence(swigCPtr.DangerousGetHandle());
    return ret;
  }

}

}
