//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.smartid {

public class OcrCharVariant : global::System.IDisposable {
  private global::System.Runtime.InteropServices.SafeHandle swigCPtr;
  protected bool swigCMemOwn;

  internal OcrCharVariant(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(cPtr, false);
  }

  internal static global::System.Runtime.InteropServices.SafeHandle getCPtr(OcrCharVariant obj) {
    return (obj == null) ? new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(global::System.IntPtr.Zero, false) : obj.swigCPtr;
  }

  ~OcrCharVariant() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr != null && swigCPtr.DangerousGetHandle() != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csSmartIdEnginePINVOKE.delete_OcrCharVariant(swigCPtr.DangerousGetHandle());
        }
        swigCPtr = new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(global::System.IntPtr.Zero, false);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public OcrCharVariant() : this(csSmartIdEnginePINVOKE.new_OcrCharVariant__SWIG_0(), true) {
  }

  public OcrCharVariant(ushort utf16_char, double confidence) : this(csSmartIdEnginePINVOKE.new_OcrCharVariant__SWIG_1(utf16_char, confidence), true) {
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public OcrCharVariant(string utf8_char, double confidence) : this(csSmartIdEnginePINVOKE.new_OcrCharVariant__SWIG_2(utf8_char, confidence), true) {
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public ushort GetUtf16Character() {
    ushort ret = csSmartIdEnginePINVOKE.OcrCharVariant_GetUtf16Character(swigCPtr.DangerousGetHandle());
    return ret;
  }

  public string GetUtf8Character() {
    string ret = csSmartIdEnginePINVOKE.OcrCharVariant_GetUtf8Character(swigCPtr.DangerousGetHandle());
    return ret;
  }

  public double GetConfidence() {
    double ret = csSmartIdEnginePINVOKE.OcrCharVariant_GetConfidence(swigCPtr.DangerousGetHandle());
    return ret;
  }

}

}
