//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.smartid {

public class OcrChar : global::System.IDisposable {
  private global::System.Runtime.InteropServices.SafeHandle swigCPtr;
  protected bool swigCMemOwn;

  internal OcrChar(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(cPtr, false);
  }

  internal static global::System.Runtime.InteropServices.SafeHandle getCPtr(OcrChar obj) {
    return (obj == null) ? new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(global::System.IntPtr.Zero, false) : obj.swigCPtr;
  }

  ~OcrChar() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr != null && swigCPtr.DangerousGetHandle() != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csSmartIdEnginePINVOKE.delete_OcrChar(swigCPtr.DangerousGetHandle());
        }
        swigCPtr = new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(global::System.IntPtr.Zero, false);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public OcrChar() : this(csSmartIdEnginePINVOKE.new_OcrChar__SWIG_0(), true) {
  }

  public OcrChar(OcrCharVariantVector ocr_char_variants, bool is_highlighted, bool is_corrected, Rectangle ocr_char_rect) : this(csSmartIdEnginePINVOKE.new_OcrChar__SWIG_1(OcrCharVariantVector.getCPtr(ocr_char_variants).DangerousGetHandle(), is_highlighted, is_corrected, Rectangle.getCPtr(ocr_char_rect).DangerousGetHandle()), true) {
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public OcrChar(OcrCharVariantVector ocr_char_variants, bool is_highlighted, bool is_corrected) : this(csSmartIdEnginePINVOKE.new_OcrChar__SWIG_2(OcrCharVariantVector.getCPtr(ocr_char_variants).DangerousGetHandle(), is_highlighted, is_corrected), true) {
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
  }

  public OcrCharVariantVector GetOcrCharVariants() {
    OcrCharVariantVector ret = new OcrCharVariantVector(csSmartIdEnginePINVOKE.OcrChar_GetOcrCharVariants(swigCPtr.DangerousGetHandle()), false);
    return ret;
  }

  public bool IsHighlighted() {
    bool ret = csSmartIdEnginePINVOKE.OcrChar_IsHighlighted(swigCPtr.DangerousGetHandle());
    return ret;
  }

  public bool IsCorrected() {
    bool ret = csSmartIdEnginePINVOKE.OcrChar_IsCorrected(swigCPtr.DangerousGetHandle());
    return ret;
  }

  public ushort GetUtf16Character() {
    ushort ret = csSmartIdEnginePINVOKE.OcrChar_GetUtf16Character(swigCPtr.DangerousGetHandle());
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public string GetUtf8Character() {
    string ret = csSmartIdEnginePINVOKE.OcrChar_GetUtf8Character(swigCPtr.DangerousGetHandle());
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public Rectangle GetRectangle() {
    Rectangle ret = new Rectangle(csSmartIdEnginePINVOKE.OcrChar_GetRectangle(swigCPtr.DangerousGetHandle()), false);
    return ret;
  }

}

}
