//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.smartid {

public class RecognitionSession : global::System.IDisposable {
  private global::System.Runtime.InteropServices.SafeHandle swigCPtr;
  protected bool swigCMemOwn;

  internal RecognitionSession(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(cPtr, false);
  }

  internal static global::System.Runtime.InteropServices.SafeHandle getCPtr(RecognitionSession obj) {
    return (obj == null) ? new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(global::System.IntPtr.Zero, false) : obj.swigCPtr;
  }

  ~RecognitionSession() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr != null && swigCPtr.DangerousGetHandle() != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csSmartIdEnginePINVOKE.delete_RecognitionSession(swigCPtr.DangerousGetHandle());
        }
        swigCPtr = new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(global::System.IntPtr.Zero, false);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public virtual RecognitionResult ProcessSnapshot(byte[] data, uint data_length, int width, int height, int stride, int channels, Rectangle roi, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessSnapshot__SWIG_0(swigCPtr.DangerousGetHandle(), data, data_length, width, height, stride, channels, Rectangle.getCPtr(roi).DangerousGetHandle(), (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessSnapshot(byte[] data, uint data_length, int width, int height, int stride, int channels, Rectangle roi) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessSnapshot__SWIG_1(swigCPtr.DangerousGetHandle(), data, data_length, width, height, stride, channels, Rectangle.getCPtr(roi).DangerousGetHandle()), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessSnapshot(byte[] data, uint data_length, int width, int height, int stride, int channels, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessSnapshot__SWIG_2(swigCPtr.DangerousGetHandle(), data, data_length, width, height, stride, channels, (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessSnapshot(byte[] data, uint data_length, int width, int height, int stride, int channels) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessSnapshot__SWIG_3(swigCPtr.DangerousGetHandle(), data, data_length, width, height, stride, channels), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessYUVSnapshot(byte[] yuv_data, uint yuv_data_length, int width, int height, Rectangle roi, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessYUVSnapshot__SWIG_0(swigCPtr.DangerousGetHandle(), yuv_data, yuv_data_length, width, height, Rectangle.getCPtr(roi).DangerousGetHandle(), (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessYUVSnapshot(byte[] yuv_data, uint yuv_data_length, int width, int height, Rectangle roi) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessYUVSnapshot__SWIG_1(swigCPtr.DangerousGetHandle(), yuv_data, yuv_data_length, width, height, Rectangle.getCPtr(roi).DangerousGetHandle()), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessYUVSnapshot(byte[] yuv_data, uint yuv_data_length, int width, int height, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessYUVSnapshot__SWIG_2(swigCPtr.DangerousGetHandle(), yuv_data, yuv_data_length, width, height, (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessYUVSnapshot(byte[] yuv_data, uint yuv_data_length, int width, int height) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessYUVSnapshot__SWIG_3(swigCPtr.DangerousGetHandle(), yuv_data, yuv_data_length, width, height), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImage(Image image, Rectangle roi, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImage__SWIG_0(swigCPtr.DangerousGetHandle(), Image.getCPtr(image).DangerousGetHandle(), Rectangle.getCPtr(roi).DangerousGetHandle(), (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImage(Image image, Rectangle roi) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImage__SWIG_1(swigCPtr.DangerousGetHandle(), Image.getCPtr(image).DangerousGetHandle(), Rectangle.getCPtr(roi).DangerousGetHandle()), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImage(Image image, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImage__SWIG_2(swigCPtr.DangerousGetHandle(), Image.getCPtr(image).DangerousGetHandle(), (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImage(Image image) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImage__SWIG_3(swigCPtr.DangerousGetHandle(), Image.getCPtr(image).DangerousGetHandle()), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImageFile(string image_file, Rectangle roi, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImageFile__SWIG_0(swigCPtr.DangerousGetHandle(), image_file, Rectangle.getCPtr(roi).DangerousGetHandle(), (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImageFile(string image_file, Rectangle roi) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImageFile__SWIG_1(swigCPtr.DangerousGetHandle(), image_file, Rectangle.getCPtr(roi).DangerousGetHandle()), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImageFile(string image_file, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImageFile__SWIG_2(swigCPtr.DangerousGetHandle(), image_file, (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImageFile(string image_file) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImageFile__SWIG_3(swigCPtr.DangerousGetHandle(), image_file), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImageData(byte[] data, uint data_length, Rectangle roi, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImageData__SWIG_0(swigCPtr.DangerousGetHandle(), data, data_length, Rectangle.getCPtr(roi).DangerousGetHandle(), (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImageData(byte[] data, uint data_length, Rectangle roi) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImageData__SWIG_1(swigCPtr.DangerousGetHandle(), data, data_length, Rectangle.getCPtr(roi).DangerousGetHandle()), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImageData(byte[] data, uint data_length, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImageData__SWIG_2(swigCPtr.DangerousGetHandle(), data, data_length, (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImageData(byte[] data, uint data_length) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImageData__SWIG_3(swigCPtr.DangerousGetHandle(), data, data_length), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImageDataBase64(string base64_image_data, Rectangle roi, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImageDataBase64__SWIG_0(swigCPtr.DangerousGetHandle(), base64_image_data, Rectangle.getCPtr(roi).DangerousGetHandle(), (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImageDataBase64(string base64_image_data, Rectangle roi) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImageDataBase64__SWIG_1(swigCPtr.DangerousGetHandle(), base64_image_data, Rectangle.getCPtr(roi).DangerousGetHandle()), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImageDataBase64(string base64_image_data, ImageOrientation image_orientation) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImageDataBase64__SWIG_2(swigCPtr.DangerousGetHandle(), base64_image_data, (int)image_orientation), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual RecognitionResult ProcessImageDataBase64(string base64_image_data) {
    RecognitionResult ret = new RecognitionResult(csSmartIdEnginePINVOKE.RecognitionSession_ProcessImageDataBase64__SWIG_3(swigCPtr.DangerousGetHandle(), base64_image_data), true);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual SessionState GetSessionState() {
    global::System.IntPtr cPtr = csSmartIdEnginePINVOKE.RecognitionSession_GetSessionState(swigCPtr.DangerousGetHandle());
    SessionState ret = (cPtr == global::System.IntPtr.Zero) ? null : new SessionState(cPtr, false);
    if (csSmartIdEnginePINVOKE.SWIGPendingException.Pending) throw csSmartIdEnginePINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public virtual void Reset() {
    csSmartIdEnginePINVOKE.RecognitionSession_Reset(swigCPtr.DangerousGetHandle());
  }

}

}
