//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace se.smartid {

public class Rectangle : global::System.IDisposable {
  private global::System.Runtime.InteropServices.SafeHandle swigCPtr;
  protected bool swigCMemOwn;

  internal Rectangle(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(cPtr, false);
  }

  internal static global::System.Runtime.InteropServices.SafeHandle getCPtr(Rectangle obj) {
    return (obj == null) ? new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(global::System.IntPtr.Zero, false) : obj.swigCPtr;
  }

  ~Rectangle() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr != null && swigCPtr.DangerousGetHandle() != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          csSmartIdEnginePINVOKE.delete_Rectangle(swigCPtr.DangerousGetHandle());
        }
        swigCPtr = new global::Microsoft.Win32.SafeHandles.SafeWaitHandle(global::System.IntPtr.Zero, false);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }

  public Rectangle() : this(csSmartIdEnginePINVOKE.new_Rectangle__SWIG_0(), true) {
  }

  public Rectangle(int x, int y, int width, int height) : this(csSmartIdEnginePINVOKE.new_Rectangle__SWIG_1(x, y, width, height), true) {
  }

  public int x {
    set {
      csSmartIdEnginePINVOKE.Rectangle_x_set(swigCPtr.DangerousGetHandle(), value);
    } 
    get {
      int ret = csSmartIdEnginePINVOKE.Rectangle_x_get(swigCPtr.DangerousGetHandle());
      return ret;
    } 
  }

  public int y {
    set {
      csSmartIdEnginePINVOKE.Rectangle_y_set(swigCPtr.DangerousGetHandle(), value);
    } 
    get {
      int ret = csSmartIdEnginePINVOKE.Rectangle_y_get(swigCPtr.DangerousGetHandle());
      return ret;
    } 
  }

  public int width {
    set {
      csSmartIdEnginePINVOKE.Rectangle_width_set(swigCPtr.DangerousGetHandle(), value);
    } 
    get {
      int ret = csSmartIdEnginePINVOKE.Rectangle_width_get(swigCPtr.DangerousGetHandle());
      return ret;
    } 
  }

  public int height {
    set {
      csSmartIdEnginePINVOKE.Rectangle_height_set(swigCPtr.DangerousGetHandle(), value);
    } 
    get {
      int ret = csSmartIdEnginePINVOKE.Rectangle_height_get(swigCPtr.DangerousGetHandle());
      return ret;
    } 
  }

}

}
